[package]
name = "ninja_fighter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# coffee = { version = "0.4", features = ["opengl"] }
ggez = "0.9.3"
bevy_ecs = "0.12.1"
serde = { version = "1.0.189", features = ["derive"] }
erased-serde = "0.4"
serde_json = "1"
typetag = "0.2"
dict = "0.1.5"
mint = "0.5.9"
nalgebra = { version = "0.32.3", features = ["serde-serialize"] }